### ISSUE TITLE
Android API 27 addNetwork return -1

### ISSUE THREAD

**Issue by aystshen** [isuPatches/WiseFy#106]
```
private int addNetworkConfiguration(WifiConfiguration wifiConfiguration) {
        int result = mWiseFyPrerequisites.getWifiManager().addNetwork(wifiConfiguration);
        if (result == WIFI_MANAGER_FAILURE) {
            if (LogUtil.isLoggable(TAG, Log.ERROR, mWiseFyConfiguration.isLoggingEnabled())) {
                Log.e(TAG, "Failed to add network");
            }
        }
        return result;
    }
```
Android API 27 addNetwork return -1

**Comment by isuPatches** [comment]
Hi there.  Are you using an emulator?  If that is the case, this is expected on some emulated devices.

Also, you may need to request the appropriate permissions.  Please see the documentation here: https://github.com/isuPatches/WiseFy/blob/2.x/documentation/permissions_example.md

**Comment by isuPatches** [comment]
@aystshen any update on this for me?  I would love to help out if at all possible

**Comment by matiplo** [comment]
have the same. 
`        val wisefy = WiseFy.brains(application).logging(true).smarts
     wisefy.addWPA2Network(ssid, password)`
and
`D/WiseFyHandlerThread: start() called on WiseFyHandlerThread
D/WiseFy: Adding WPA2 network with SSID <here_my_ssid>
 E/WiseFy: Failed to add network`
wifiManager return -1

I have all permissions(location obtained earlier in my functionality by calling Settings activity) and debugging on real device

**Comment by isuPatches** [comment]
Hey there!  

I was able to reproduce the issue locally finally.  It seems this bug will fixed in the 2.1.x version of the library.  I apologize for the trouble.  

@aystshen  and @matiplo, can you please try to use the 2.1.x  aar here:  https://github.com/isuPatches/WiseFy/releases/tag/v2.1.0-BETA1 and let me know the results.  Thank you for the support and for using the library!  I hope to have an official 2.1.x release by the end of the month.

For historical purposes here are my logs from reproducing:

> 06-20 08:06:58.301 7532-8293/com.isupatches.wisefysample D/a: Adding WPA2 network with SSID <MY_SSID>
> 06-20 08:06:58.303 868-8780/? I/WifiService: addOrUpdateNetwork uid=10673
> 06-20 08:06:58.303 868-8780/? I/addOrUpdateNetwork:  uid = 10673 SSID <MY_SSID>nid=-1
> 06-20 08:06:58.304 868-1143/? E/WifiConfigManager: Cannot find network with networkId -1 or configKey <MY_SSID>WPA_PSK
> 06-20 08:06:58.304 868-1143/? E/WifiConfigurationUtil: validateSsid failed: malformed string: <MY_SSID>
> 06-20 08:06:58.304 868-1143/? E/WifiConfigManager: Cannot add network with invalid config
>     Failed to add/update network <MY_SSID>
> 06-20 08:06:58.304 7532-8293/com.isupatches.wisefysample E/a: Failed to add network
> 06-20 08:06:58.329 647-3611/? D/audio_hw_primary: out_write: retry previous failed cal level set
> 06-20 08:06:58.747 868-1429/? D/WificondControl: Scan result ready event
> 06-20 08:06:58.754 868-1151/? D/WificondScannerImpl: Filtering out 3 scan results.
> 06-20 08:06:58.758 868-1143/? W/WifiConfigManager: Looking up network with invalid networkId -1
> 06-20 08:06:58.767 868-1143/? W/WifiConfigManager: Looking up network with invalid networkId -1

On the 2.1.x version the logs are different.  They look like this:

> 06-20 08:11:56.172 9158-9344/com.isupatches.wisefysample D/WiseFy: Adding network with SSID: "<MY_SSID>" had result: 6
> 06-20 08:11:56.178 9158-9344/com.isupatches.wisefysample D/AddNetworkViewModel: WPA2 network added! Network id: 6, Network configuration: ID: -1 SSID: "<MY_SSID>"

Reasons WifiManager when adding a network can fail:

1.  Password is less than 8 characters
2.  Wifi is not accessible (i.e. emulators most lilkely will return -1 and a live device is recommeneded for testing)
3.  The wifi configuration already is present on the phone

**Comment by isuPatches** [comment]
@matiplo @aystshen Any luck with the 2.1.x version?  I would like to make sure that it is working for you before I close this ticket.  Thanks!

**Comment by aystshen** [comment]
Thank you all, this problem has been solved because the acquired ssid has a "" sign, and I removed it, making it impossible to add the network successfully.

**Comment by isuPatches** [comment]
Thanks you!  Please don't hesitate to reopen or open a new issue if you spot something that's wrong.

**Comment by fotix** [comment]
Hello ! I'm having this issue in 8.1 and also not getting the wifi networks around in all my 8.0 phones (even if it works perfectly in 6.0 , 6.0.1, 7.0  and so on). Today i will test with the BETA version and come back to my findings even though this is already closed

**Comment by matiplo** [comment]
hello, I can check if this really works when you release the official version of 2.1.x (I cannot use beta version in my project). When the official release is scheduled?

**Comment by isuPatches** [comment]
@matiplo The official release I'm hoping to have within the next 2-3 weeks.  I appreciate your patience.

**Comment by gaafouri** [comment]
> Merci à tous, ce problème a été résolu car le ssid acquis a un signe "", et je l'ai supprimé, ce qui rend impossible l'ajout du réseau avec succès.

hi @ aystshen a hello is that you can help me and explain to me how you have solve it

**Comment by gaafouri** [comment]
Hi @aystshen a
bonjour est que vous pouvez m'aider et m'expliquer comment vous l'avez résolu

**Comment by aystshen** [comment]
Hello, I was at the time because the SSID had a [""] symbol causing addNetwork to return -1, so we processed the SSID and removed the [""] symbol. E.g:
The SSID obtained is: "TP-LINK", we need to change it to: TP-LINK.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月26日(星期天) 晚上6:44
收件人:&nbsp;"isuPatches/WiseFy"<WiseFy@noreply.github.com&gt;;
抄送:&nbsp;"申海波"<ayst.shen@foxmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [isuPatches/WiseFy] Android API 27 addNetwork return -1 (#106)





 
Hi @aystshen a
 bonjour est que vous pouvez m'aider et m'expliquer comment vous l'avez résolu

**Comment by gaafouri** [comment]
Hi @aystshen 
thank you very much
