### ISSUE TITLE
Is there support for async or observable state changing?

### ISSUE THREAD

**Issue by Edris89** [isuPatches/WiseFy#134]
Hi there I am trying to get the state of the wifi but the UI thread can not be interrupted.
It has to be a observable of async

Does this library support that?
PS: Just tested the features of this library and it works out of the box.
Great documentation
Great work.
Just added a star for you.
Keep up the good work

**Comment by isuPatches** [comment]
@Edris89 

The async APIs should be non-thread blocking, but I'm curious about what kind of updates you are looking for. 

With the update to Android P, I could potentially return a stream from the network change listener with when connectivity is established, lost, losing, etc.  Is that the kind of functionality you were thinking of?

This would be a good idea for a 4.1 release I would think.

**Comment by isuPatches** [comment]
Also, thank you so much for using the library and the feedback/support!

**Comment by isuPatches** [comment]
Please reopen with more details once you have a time to respond.
