### ISSUE TITLE
Android 10 support status

### ISSUE THREAD

**Issue by dariopellegrini** [isuPatches/WiseFy#146]
Thank you for creating an issue to improve this library! Please check Please check [the current issues](https://github.com/isuPatches/WiseFy/issues) to make sure that the improvement isn't already being worked on.

**Description**
Android 10 came out on September 2019. I'm asking if a WiseFy update for Android 10 will be released. I know it is on to-do, but there is no update since the beginning of 2020.

**Reason**
Support for new services and Android updates.

Thank you for your work. WiseFy saved me a lot of work.

**Comment by isuPatches** [comment]
Hey @dariopellegrini, I understand that Android 10/Android 11 support has taken a very long time.   I am glad the library has been useful to you and apologize for being a bottleneck.  I fully intend to add this support to the library, but have been struggling to find the time as it would require all new APIs and deprecation of some of the older ones.  I have a WIP branch that I am testing for the new connection and other APIs so this effort has started.  Android has with the 10th iteration completely changed how network connection and suggestions work and I have lagged behind as I am trying to devise a long term strategy for supporting new OS'es without having to rewrite APIs from scratch.  

I am also willing to consider community and outside help/support to accomplish this.

**Comment by isuPatches** [comment]
https://github.com/isuPatches/WiseFy/pull/147 There's been progress with the connect and network suggestions APIs, I am still learning more about the new expectations, but a draft PR will at least show that I'm actively pursuing Android R as well

**Comment by isuPatches** [comment]
5.0.0-RC2 has been released with support for Android P, Q, and R
