### ISSUE TITLE
withContext method not public

### ISSUE THREAD

**Issue by clamentsanz** [isuPatches/WiseFy#41]
Hi,

When I try to make : 
`        WiseFy mWiseFy = new WiseFy.withContext(this).getSmarts();`

I have this error : 

> "withContext(android.context.Context)" is not public in 'com.isupatches.wisefly.WiseFy.withContext'. Cannot be accessed from outside package.

**Comment by clamentsanz** [comment]
thanks 👍  how can I test the patch ?

**Comment by isuPatches** [comment]
@clamentsanz can you please try the 1.0.8 version from https://github.com/isuPatches/WiseFy/releases/tag/v1.0.8  or from mavenCentral/JCenter.

This should resolve your issue.  Please reopen if needed.
