### ISSUE TITLE
Method not public?

### ISSUE THREAD

**Issue by ysyyork** [isuPatches/WiseFy#51]
I'm wondering why all the methods are protected? Am I missing something? I can't use them after I create the wisefy object.

**Comment by clamentsanz** [comment]
Hi, 
It's now working with WiseFy.withContext() in the 1.0.8 thanks :)
But I have the same problem with the function getNearbyAccessPoints().

**Comment by isuPatches** [comment]
Oh my...this is really embarrassing...I will adjust my tests to capture scope issues.

**Comment by isuPatches** [comment]
Please try v1.0.9
