### ISSUE TITLE
method not public with getNearbyAccessPoints()

### ISSUE THREAD

**Issue by clamentsanz** [isuPatches/WiseFy#52]
Hi,
It's now working with WiseFy.withContext() in the 1.0.8 thanks :)
But I have the same problem with the function getNearbyAccessPoints().

**Comment by isuPatches** [comment]
Thank you so much for using and providing feedback on this library...this is the same as #51. I got a little overzealous cleaning up lint errors, but have readdressed the testing package to account for this.

**Comment by isuPatches** [comment]
Please try v1.0.9

**Comment by clamentsanz** [comment]
It's working now! thanks!
