### ISSUE TITLE
NullPointerException exception with isDeviceConnectedToMobileOrWifiNetwork()

### ISSUE THREAD

**Issue by clamentsanz** [isuPatches/WiseFy#57]
Hi,

When I use : `mWiseFy.isDeviceConnectedToMobileOrWifiNetwork()`

I have this error : 

> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
>                                                                          at com.isupatches.wisefy.WiseFy.isDeviceConnectedToMobileOrWifiNetwork(WiseFy.java:578)

It seem sometimes it's working and sometimes not...

**Comment by isuPatches** [comment]
I can fix that one too with the next release...that's because for safety:

`  if (networkInfo.isConnected() && networkInfo.isAvailable())  {`
should be:

`if (networkInfo != null && networkInfo.isConnected() && networkInfo.isAvailable()) {`

I bet in some cases networkInfo is null.

**Comment by isuPatches** [comment]
Please try 1.0.10 when you get a chance...thank you :)
