### ISSUE TITLE
mWiseFy.addWPA2Network with methods (onConnect, on Fail)

### ISSUE THREAD

**Issue by clamentsanz** [isuPatches/WiseFy#58]
Hi,

Just a suggestion, can you implement some methods after the function mWiseFy.addWPA2Network() for example : 
@override
public void onSuccess() {}

@override
public void onFail() {}
?

It would be awesome :)

**Comment by isuPatches** [comment]
Hey there :)  The work week caught up with me...let me think on this and see if I can come up with a proposal for callbacks like that.  I'm not sure they would make sense for every method, but it could be nice to have that layer.

**Comment by isuPatches** [comment]
I think I'm going to move forward with this idea...I'm proposing method signatures like this:

`    public void addWEPNetwork(String ssid, String password, WiseFySuccessCallback onSuccess, WiseFyFailureCallback onFailure) {`

And then it could be implemented like this:

```
 mWiseFy.addOpenNetwork(OPEN_NETWORK_SSID, new WiseFy.WiseFySuccessCallback() {
            @Override
            public void call(WifiConfiguration wifiConfiguration) {

            }
        }, new WiseFy.WiseFyFailureCallback() {
            @Override
            public void call(Integer returnCode) {
                
            }
        });
```

Or something similar...thoughts?  This will require some time and the naming of methods and callbacks are subject to change...the tests are also setup pretty linearly now and I would want to document the new updates, but I can get onboard with this architecture...it feels very RxJava-ish.

**Comment by isuPatches** [comment]
A complete async API will be available in 2.x branch.  Each method will have it's own set of callbacks and will be run on a WisefyHandlerThread.  This will also cause user's to have to call a method to cleanup the thread at their discretion.  This is also related to #60 and #63.

**Comment by isuPatches** [comment]
I'm hoping to release a 2.0.0 within the next 2 weeks...I have some tests and documentation to wrap up but the API itself is finalized.  I can provide a BETA if you are overly curious :)

**Comment by clamentsanz** [comment]
Oh yes! I would like to see the beta!

**Comment by isuPatches** [comment]
https://github.com/isuPatches/WiseFy/releases/tag/v2.0.0-BETA1 :)  

It also should now be available through gradle with `compile 'com.isupatches:wisefy:2.0.0-BETA1'`
