### ISSUE TITLE
Wifi scanning when connected to network

### ISSUE THREAD

**Issue by daniilkrant** [isuPatches/WiseFy#86]
Scanning of networks doesn't work when connected to Wifi hotspot

**Comment by isuPatches** [comment]
Do you have the appropriate location permission listed in the documentation https://github.com/isuPatches/WiseFy/blob/2.x/documentation/permissions_example.md

I'm wondering if it never works on your device because you are missing that.

What type and version of Android are you using and what type of Hotspot?  Are you using one of the regex search functions and may I also see how you are trying to scan?

**Comment by daniilkrant** [comment]
Sorry for long response. All permissions are in manifest and granted. Android 6,5 (Samsung, Meizu, Lenovo). 
Here is code which I use:
` List<ScanResult> scans = mWiseFy.getNearbyAccessPoints(true);`
Scanning is working, but when I connected to any Wifi point it just return empty List

**Comment by isuPatches** [comment]
I will see if I can't replicate when I have a spare moment

**Comment by daniilkrant** [comment]
maybe you have sample app. i will test it in my conditions, and detect is this a bug(or something like that) or troubles in my code?

**Comment by isuPatches** [comment]
That was the route I was going to go more than likely :)  Sorry if it takes a few days...I'm pretty busy.

**Comment by daniilkrant** [comment]
OK, it's normal way)

**Comment by isuPatches** [comment]
I plan on looking at this hopefully this weekend.  Thank you for your patience.

**Comment by isuPatches** [comment]
I had a spare cycle and made this sample: https://github.com/isuPatches/WiseFySample which works for me locally.

` List: [SSID: CantTouchThis5g, ...]`

Question...if you open your network settings on your Android phone, is it able to see the other networks?  I did some playing around and when the Android device had WiFi off the list would rightfully return [].  I'm wondering if there are cases on Hot Spots that are similar where once connected, other networks are no longer reported.  If that is the issue, I would have to think a lot about a solution.

**Comment by daniilkrant** [comment]
Ookay, you know
It's working
I simulated my situation, adn it works just fine
Sorry for worrying you
Troubles in my side
Perhaps, now lib has a sample)
//By the way
Is that output built in lib?
```
D/WiseFySearch: Found new wifi network
D/WiseFySearch: SSID 1: UNTC_7, SSID 2: dir-615
```

**Comment by isuPatches** [comment]
Glad to hear!  Yes, that is part of the libraries logging which is disabled by default and enabled by the logging parameter on the builder:

`WiseFy mWiseFy = new WiseFy.brains(getActivity()).logging(true).getSmarts();`

It's also nice to have a sample :)  Thank you for your feedback and usage.
